spring.application.name=workout-logger

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workout_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:workoutapp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:WorkOut1!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true